# Generated by Django 4.2.27 on 2025-12-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("iso2", models.CharField(blank=True, max_length=2, null=True)),
                ("dafif", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plane",
            fields=[
                ("plane_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("iata", models.CharField(blank=True, max_length=3, null=True)),
                ("icao", models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("airport_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("iata", models.CharField(blank=True, max_length=3, null=True)),
                ("icao", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("altitude_ft", models.IntegerField(blank=True, null=True)),
                (
                    "timezone_hrs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("dst", models.CharField(blank=True, max_length=1, null=True)),
                ("tz", models.CharField(blank=True, max_length=60, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="airports",
                        to="openflights.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Airline",
            fields=[
                ("airline_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("alias", models.CharField(blank=True, max_length=200, null=True)),
                ("iata", models.CharField(blank=True, max_length=3, null=True)),
                ("icao", models.CharField(blank=True, max_length=4, null=True)),
                ("callsign", models.CharField(blank=True, max_length=120, null=True)),
                ("active", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="airlines",
                        to="openflights.country",
                    ),
                ),
            ],
        ),
    ]
